version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  js-build:
    docker:
      - image: cimg/node:16.8.0-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Running JS linting and unit test
          command: |
            npm run lint:js
            npm run test:js
  php-build:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run:
          name: Linting and testing PHP
          command: |
            composer install
            composer lint
            composer test
  e2e-test:
    docker:
      - image: cimg/node:16.8.0-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Running e2e tests
          command: |
            npm run wp-env start
            npm run test:e2e

workflows:
  test-all:
    jobs:
      - js-build
      - php-build
      - e2e-test
