# https://circleci.com/docs/2.0/config-intro/

version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  js-build:
    docker:
      - image: cimg/node:14.18
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Running JS linting and unit test
          command: |
            npm run lint:js
            npm run test:js

  php-lint:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run:
          name: Linting PHP
          command: |
            composer i
            composer lint

  php-test:
    parameters:
      php-version-number:
        type: string
    docker:
      - image: cimg/php:<< parameters.php-version-number >>
    steps:
      - checkout
      - run:
          name: Testing PHP
          command: |
            composer i
            composer test

  e2e-test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - setup_remote_docker
      - run:
          name: Install packages for Puppeteer
          command: |
            apt-get update
            apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2
            libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4
            libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0
            libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1
            libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1
            libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release
            xdg-utils wget
      - checkout
      - node/install
      - node/install-packages
      - run:
          name: Running e2e tests
          command: |
            docker run hello-world
            npm run wp-env start
            npm run test:e2e
      - store_artifacts:
          path: artifacts

workflows:
  test-flow:
    jobs:
      - js-build
      - php-lint
      - php-test:
          requires:
            - php-lint
          matrix:
            parameters:
              php-version-number: [ '7.3', '7.4', '8.0', '8.1' ]
      - e2e-test
